openapi: 3.0.3
info:
  title: Additional Properties - No Schema
  version: "1.0"
paths: {}
components:
  schemas:
    ReffingNullableAdditionalProperties:
      allOf:
        - $ref: "#/components/schemas/NullableAdditionalProperties"
        - type: object
          additionalProperties:
            nullable: true
          properties:
            two:
              type: string
    NullableAdditionalProperties:
      type: object
      properties:
        one:
          type: string
      additionalProperties:
        nullable: true
