openapi: 3.1.0
info:
  title: Responses
  version: '1.0.0'
paths:
  /test:
    get:
      responses:
        200:
          description: OK
          content:
            image/*:
              schema:
                type: string
                format: binary
