openapi: 3.0.0
info:
  title: Example
  version: '1.0.1'
paths:
  /test1:
    get:
      responses:
        200:
          description: Testing
          content:
            application/json:
              schema:
                $ref: './external-part.yml#/paths/%2Ftest-part/get/responses/200/content/application%2Fjson/schema'
