openapi: 3.0.0
info:
  title: Example
  version: '1.0.1'
paths:
  /test1:
    get:
      responses:
        200:
          description: My response
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: string
  /test2:
    get:
      responses:
        200:
          $ref: '#/paths/%2Ftest1/get/responses/200'
