---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: allOf with a map
paths: {}
components:
  schemas:
    Parent:
      properties:
        name:
          type: string
    Child:
      allOf:
        - $ref: '#/components/schemas/Parent'
        - type: object
          # As this object has addditionalProperties and no properties, we determine it to be a map
          additionalProperties:
            type: string
    Standalone:
      type: object
      # As this object has addditionalProperties and no properties, we determine it to be a map
      additionalProperties:
        type: string
