---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
  description: An allOf with properties of conflicting types
paths: {}
components:
  schemas:
    Child:
      allOf:
        - type: object
          properties:
            childName:
              type: string
        - type: object
          properties:
            childName:
              type: integer
              