openapi: 3.0.3
info:
  title: Multipart
  version: '1.0'
paths:
  /object/create:
    post:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                Info:
                  type: object
                  properties:
                    name:
                      type: string
                    size:
                      type: number
                File:
                  type: string
                  format: binary
            encoding:
              Info:
                contentType: text/plain
      responses:
        200:
          description: OK
