openapi: 3.0.3
info:
  title: Multipart
  version: '1.0'
paths:
  /object/update:
    post:
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              properties:
                info:
                  type: object
                  properties:
                    name:
                      type: string
                    size:
                      type: number
      responses:
        200:
          description: OK
