---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
paths: {}
components:
  schemas:
    Ford:
      type: object
      properties:
        messages:
          type: array
          items:
            type: string
            enum: [Good, Bad, Ugly]
