---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
paths: {}
components:
  schemas:
    MyResponseType:
      oneOf:
      - $ref: '#/components/schemas/Cat'
      - $ref: '#/components/schemas/Dog'
      - $ref: '#/components/schemas/Lizard'
    Cat:
      type: object
      properties:
        name:
          type: string
    Dog:
      type: object
      properties:
        name:
          type: string
        bark:
          type: string
    Lizard:
      type: object
      properties:
        lovesRocks:
          type: boolean
