---
openapi: '3.0.3'
info:
  version: 1.0.1
  title: Example
paths: {}
components:
  schemas:
    MyResponseType:
      oneOf:
        - $ref: '#/components/schemas/Cat'
        - $ref: '#/components/schemas/Dog'
        - $ref: '#/components/schemas/Lizard'
      discriminator:
        propertyName: petType
    Cat:
      type: object
      properties:
        name:
          type: string
    Dog:
      type: object
      properties:
        bark:
          type: string
    Lizard:
      type: object
      properties:
        lovesRocks:
          type: boolean
