openapi: 3.0.0
info:
  title: Example
  version: '1.0.1'
paths: {}
components:
  schemas:
    MyResponse:
      description: My response
      type: object
      discriminator:
        propertyName: myType
      properties:
        myType:
          type: string
    MyGoodResponse:
      allOf:
        - $ref: '#/components/schemas/MyResponse'
        - type: object
          properties:
            good:
              type: boolean
    MyBadResponse:
      allOf:
        - $ref: '#/components/schemas/MyResponse'
        - type: object
          properties:
            bad:
              type: boolean
