openapi: 3.0.0
info:
  title: Example
  version: '1.0.1'
paths:
  /test1:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './external-discriminators-part.yml#/components/schemas/MyResponse'
