openapi: 3.0.0
info:
  title: Example
  version: '1.0.1'
paths: {}
components:
  responses:
    MyResponse:
      description: My response
      content:
        application/json:
          schema:
            type: object
            properties:
              value:
                type: string
